<?php

use yozh\base\components\db\Migration;
use yozh\base\components\db\Schema;
use yozh\properties\models\PropertiesModel;

/**
 * Class m180301_142414_add_column_to_properties_table
 */
class m000000_000000_property_table_dev extends Migration
{
	protected static $_table = 'property';
	
	public function _getColumns( $columns = [] )
	{
		return array_merge_recursive( parent::_getColumns( $columns ), [
			'name'   => $this->string()->notNull()->after( 'model' ),
			'type'   => $this->enum( PropertiesModel::getInputsTypes() )
			                 ->notNull()
			                 ->defaultValue( PropertiesModel::INPUT_TYPE_STRING )
			                 ->after( 'name' ),
			'widget' => $this->enum( PropertiesModel::getWidgetsTypes() )->notNull()->defaultValue( PropertiesModel::getDefaultWidget()['name'] )->after( 'type' ),
			'config' => $this->text()->null()->after( 'widget' ),
			
			'validators' => $this->text()->null()->after( 'config' ),
			
			'order'  => $this->integer()->null()->after( 'validators' ),
			'parent' => $this->integer()->null()->after( 'order' ),
			
			PropertiesModel::INPUT_TYPE_STRING => $this->string()->null()->after( 'validators' ),
			PropertiesModel::INPUT_TYPE_TEXT   => $this->text()->null()->after( PropertiesModel::INPUT_TYPE_STRING ),
			
			PropertiesModel::INPUT_TYPE_INTEGER => $this->integer()->null()->after( PropertiesModel::INPUT_TYPE_TEXT ),
			PropertiesModel::INPUT_TYPE_DECIMAL => $this->double()->null()->after( PropertiesModel::INPUT_TYPE_INTEGER ),
			
			PropertiesModel::INPUT_TYPE_DATE     => $this->date()->null()->after( PropertiesModel::INPUT_TYPE_DECIMAL ),
			PropertiesModel::INPUT_TYPE_TIME     => $this->time()->null()->after( PropertiesModel::INPUT_TYPE_DATE ),
			PropertiesModel::INPUT_TYPE_DATETIME => $this->dateTime()->null()->after( PropertiesModel::INPUT_TYPE_TIME ),
		] );
	}
	
	public function safeUp( $params = [] )
	{
		$params['mode'] = self::ALTER_MODE_IGNORE;
		
		parent::safeUp( $params ); // TODO: Change the autogenerated stub
		
		return false;
	}
	
	
}
